version: "3.6"
services:
  dynamodb:
    image: amazon/dynamodb-local:latest
    container_name: dynamodb
    command: ["-jar", "DynamoDBLocal.jar", "-sharedDb", "-inMemory"]
    ports:
      - 9999:8000

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/error.log:/etc/nginx/error_log.log
#      - ./nginx/cache/:/etc/nginx/cache
#      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443

  backend:
    build: ./backend/
    container_name: backend
    expose:
      - "8000"
    secrets:
      - my_secret
    environment:
      - RUN_MODE=local
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=us-west-1

  frontend:
    build: ./frontend-bs4
    container_name: frontend
    volumes:
      - ./frontend-bs4/public:/app/public/
      - ./frontend-bs4/src:/app/src/
      - ./frontend-bs4/package.json:/app/package.json
    expose:
      - "3000"

secrets:
  my_secret:
    file: ./secrets.yml
