version: "3.6"
services:
#  nginx:
#    image: nginx:latest
#    container_name: production_nginx
#    volumes:
#      - ./nginx.prod.conf:/etc/nginx/nginx.conf
#    #      - ./nginx/error.log:/etc/nginx/error_log.log
#    #      - ./nginx/cache/:/etc/nginx/cache
#    #      - /etc/letsencrypt/:/etc/letsencrypt/
#    ports:
#      - 80:80
#      - 443:443
#
  backend:
    image: andrewkho/starva-stumit-backend
    restart: always

    container_name: backend
    expose:
      - "8000"
    secrets:
      - my_secret
    environment:
      - RUN_MODE=prod

  frontend:
    image: andrewkho/starva-stumit-frontend
    restart: always
    container_name: frontend
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
      - ./public.pem:/etc/ssl/public.pem
      - ./private.pem:/etc/ssl/private.pem
    ports:
      - 443:443

secrets:
  my_secret:
    file: ./secrets.yml
