version: "3.6"
services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
#      - ./nginx/error.log:/etc/nginx/error_log.log
#      - ./nginx/cache/:/etc/nginx/cache
#      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443

  backend:
    build: ./backend/
    container_name: backend
    expose:
      - "8000"
    # entrypoint: "cat /run/secrets/strava_token_key_bin"
    secrets:
      - my_secret
    environment:
      - RUN_MODE=local

  frontend:
    build: ./frontend-bs4
    container_name: frontend
    volumes:
      - ./frontend-bs4/public:/app/public/
      - ./frontend-bs4/src:/app/src/
      - ./frontend-bs4/package.json:/app/package.json
    expose:
      - "3000"

secrets:
  my_secret:
    file: ./secrets.yml
